version: 2
updates:
    - package-ecosystem: gomod
      directory: /
      schedule:
        interval: daily
      ignore:
        - dependency-name: github.com/onsi/gomega
      labels:
        - semver:patch
        - type:dependency-upgrade
