github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/spring-boot","gcr.io/paketo-buildpacks/spring-boot"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- id:   spring-cloud-bindings
  name: Spring Cloud Bindings 1
  uses: docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  version_pattern: "^1\\.[\\d]+\\.[\\d]+"
  with:
    uri:         https://repo1.maven.org/maven2
    group_id:    org.springframework.cloud
    artifact_id: spring-cloud-bindings
    version_regex: "^1\\.[\\d]+\\.[\\d]+$"
    source_classifier: sources
- id:   spring-cloud-bindings
  name: Spring Cloud Bindings 2
  uses: docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  version_pattern: "^2\\.[\\d]+\\.[\\d]+"
  with:
    uri:         https://repo1.maven.org/maven2
    group_id:    org.springframework.cloud
    artifact_id: spring-cloud-bindings
    version_regex: "^2\\.[\\d]+\\.[\\d]+$"
    source_classifier: sources
